In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import  ColumnTransformer

In [4]:
df = pd.read_csv("bikes.csv")

In [5]:
df.head(5)

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19 bhp,63500
1,Royal Enfield Classic 350cc 2016,2016,50000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19.80 bhp,115000
2,Hyosung GT250R 2012,2012,14795 Km,first owner,hyderabad,\r\n\r\n 30 kmpl,28 bhp,300000
3,Bajaj Dominar 400 ABS 2017,2017,Mileage 28 Kms,first owner,pondicherry,\r\n\r\n 28 Kms,34.50 bhp,100000
4,Jawa Perak 330cc 2020,2020,2000 Km,first owner,bangalore,\r\n\r\n,30 bhp,197500

In [6]:
df.columns

Index(['model_name', 'model_year', 'kms_driven', 'owner', 'location',
       'mileage', 'power', 'price'],
      dtype='object')

In [7]:
sel_col = ["model_name", "model_year", "kms_driven","mileage", "power"]

In [8]:
target = ["price"]

In [9]:
 X = df[sel_col]

In [10]:
y = df[target]

In [11]:
y

       price
0      63500
1     115000
2     300000
3     100000
4     197500
...      ...
7852   55000
7853   28000
7854   61740
7855   49000
7856   65000

[7857 rows x 1 columns]

In [12]:
df.head(5)

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19 bhp,63500
1,Royal Enfield Classic 350cc 2016,2016,50000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19.80 bhp,115000
2,Hyosung GT250R 2012,2012,14795 Km,first owner,hyderabad,\r\n\r\n 30 kmpl,28 bhp,300000
3,Bajaj Dominar 400 ABS 2017,2017,Mileage 28 Kms,first owner,pondicherry,\r\n\r\n 28 Kms,34.50 bhp,100000
4,Jawa Perak 330cc 2020,2020,2000 Km,first owner,bangalore,\r\n\r\n,30 bhp,197500

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7857 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7857 non-null   object
 1   model_year  7857 non-null   int64
 2   kms_driven  7857 non-null   object
 3   owner       7857 non-null   object
 4   location    7838 non-null   object
 5   mileage     7846 non-null   object
 6   power       7826 non-null   object
 7   price       7857 non-null   int64
dtypes: int64(2), object(6)
memory usage: 491.2+ KB

In [14]:
df.isna().sum()

model_name     0
model_year     0
kms_driven     0
owner          0
location      19
mileage       11
power         31
price          0
dtype: int64

In [15]:
df = df.dropna()

In [16]:
df.isnull().sum()

model_name    0
model_year    0
kms_driven    0
owner         0
location      0
mileage       0
power         0
price         0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7796 non-null   object
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   object
 6   power       7796 non-null   object
 7   price       7796 non-null   int64
dtypes: int64(2), object(6)
memory usage: 548.2+ KB

In [18]:
df.head()

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19 bhp,63500
1,Royal Enfield Classic 350cc 2016,2016,50000 Km,first owner,hyderabad,\r\n\r\n 35 kmpl,19.80 bhp,115000
2,Hyosung GT250R 2012,2012,14795 Km,first owner,hyderabad,\r\n\r\n 30 kmpl,28 bhp,300000
3,Bajaj Dominar 400 ABS 2017,2017,Mileage 28 Kms,first owner,pondicherry,\r\n\r\n 28 Kms,34.50 bhp,100000
4,Jawa Perak 330cc 2020,2020,2000 Km,first owner,bangalore,\r\n\r\n,30 bhp,197500

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7796 non-null   object
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   object
 6   power       7796 non-null   object
 7   price       7796 non-null   int64
dtypes: int64(2), object(6)
memory usage: 548.2+ KB

In [20]:
df['kms_driven'] = pd.to_numeric(
    df['kms_driven'].str.extract('(\d+)')[0], 
    errors='coerce'
)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7793 non-null   float64
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   object
 6   power       7796 non-null   object
 7   price       7796 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 548.2+ KB

In [22]:
df['mileage'] = pd.to_numeric(
    df['mileage'].str.extract('(\d+)')[0], 
    errors='coerce'
)

In [23]:
df['mileage'] = df['mileage'].fillna(df['mileage'].mean())

In [24]:
df.isna().sum()

model_name    0
model_year    0
kms_driven    3
owner         0
location      0
mileage       0
power         0
price         0
dtype: int64

In [25]:
df['power'] = pd.to_numeric(
    df['power'].str.extract('(\d+)')[0], 
    errors='coerce'
)

In [26]:
df.tail()

,model_name,model_year,kms_driven,owner,location,mileage,power,price
7852,Yamaha YZF-R15 150cc 2011,2011,7000.0,first owner,agra,42.0,16,55000
7853,Bajaj Discover 100cc 2015,2015,80.0,first owner,delhi,80.0,7,28000
7854,Bajaj Pulsar 180cc 2016,2016,6407.0,first owner,bangalore,65.0,17,61740
7855,Bajaj V15 150cc 2016,2016,7524.0,first owner,bangalore,57.0,11,49000
7856,Bajaj Pulsar 220cc 2016,2016,15000.0,first owner,chennai,38.0,21,65000

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7793 non-null   float64
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   float64
 6   power       7796 non-null   int64
 7   price       7796 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 548.2+ KB

In [28]:
df.isna().sum()

model_name    0
model_year    0
kms_driven    3
owner         0
location      0
mileage       0
power         0
price         0
dtype: int64

In [29]:
df['kms_driven'] = df['kms_driven'].fillna(df['kms_driven'].mean())

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7796 non-null   float64
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   float64
 6   power       7796 non-null   int64
 7   price       7796 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 548.2+ KB

In [31]:
df['mileage'] = df['mileage'].astype(int)

In [32]:
df['kms_driven'] = df['kms_driven'].astype(int)

In [33]:
df.head()

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000,first owner,hyderabad,35,19,63500
1,Royal Enfield Classic 350cc 2016,2016,50000,first owner,hyderabad,35,19,115000
2,Hyosung GT250R 2012,2012,14795,first owner,hyderabad,30,28,300000
3,Bajaj Dominar 400 ABS 2017,2017,28,first owner,pondicherry,28,34,100000
4,Jawa Perak 330cc 2020,2020,2000,first owner,bangalore,44,30,197500

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   model_year  7796 non-null   int64
 2   kms_driven  7796 non-null   int64
 3   owner       7796 non-null   object
 4   location    7796 non-null   object
 5   mileage     7796 non-null   int64
 6   power       7796 non-null   int64
 7   price       7796 non-null   int64
dtypes: int64(5), object(3)
memory usage: 548.2+ KB

In [35]:
cat_cols = ["model_name", "owner","location"]

In [36]:
num_cols =["model_year","kms_driven","mileage","power"]

In [37]:
target = "price"
X = df[cat_cols + num_cols]
y = df[target]

In [38]:
preprocess = ColumnTransformer(
    transformers= [
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ("num", "passthrough", num_cols)
    ]    
)

In [39]:
model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

In [40]:
clf = Pipeline(
    steps=[
        ("preprocess",preprocess),
        ("model",model)
    ]
)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [42]:
clf.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model_name', 'owner',
                                                   'location']),
                                                 ('num', 'passthrough',
                                                  ['model_year', 'kms_driven',
                                                   'mileage', 'power'])])),
                ('model',
                 RandomForestRegressor(n_estimators=300, n_jobs=-1,
                                       random_state=42))])

In [43]:
y_pred = clf.predict(X_test)

In [44]:
print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_squared_error(y_test, y_pred))

R2: 0.8945118462855487
MAE: 1482245807.7648575

In [45]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)

print("R2 :", r2_score(y_test, y_pred))
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)

R2 : 0.8945118462855487
MAE: 15085.300575067615
MSE: 1482245807.7648575
RMSE: 1482245807.7648575

In [46]:
import joblib

# yahi pipeline hai jisme ColumnTransformer + RandomForest hai
# naam tumne 'pipe' rakha tha:
# pipe.fit(X_train, y_train) already ho chuka hai

joblib.dump(clf, "used_bike_price_model.joblib")

['used_bike_price_model.joblib']

In [47]:
import sklearn
print(sklearn.__version__)

1.6.1

In [48]:
print(X.columns.tolist())

['model_name', 'owner', 'location', 'model_year', 'kms_driven', 'mileage', 'power']

In [49]:
print("cat_cols:", cat_cols)
print("num_cols:", num_cols)

cat_cols: ['model_name', 'owner', 'location']
num_cols: ['model_year', 'kms_driven', 'mileage', 'power']

In [50]:
num_cols

['model_year', 'kms_driven', 'mileage', 'power']

In [51]:
X.head()

,model_name,owner,location,model_year,kms_driven,mileage,power
0,Bajaj Avenger Cruise 220 2017,first owner,hyderabad,2017,17000,35,19
1,Royal Enfield Classic 350cc 2016,first owner,hyderabad,2016,50000,35,19
2,Hyosung GT250R 2012,first owner,hyderabad,2012,14795,30,28
3,Bajaj Dominar 400 ABS 2017,first owner,pondicherry,2017,28,28,34
4,Jawa Perak 330cc 2020,first owner,bangalore,2020,2000,44,30

In [52]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7796 entries, 0 to 7856
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7796 non-null   object
 1   owner       7796 non-null   object
 2   location    7796 non-null   object
 3   model_year  7796 non-null   int64
 4   kms_driven  7796 non-null   int64
 5   mileage     7796 non-null   int64
 6   power       7796 non-null   int64
dtypes: int64(4), object(3)
memory usage: 487.2+ KB

In [55]:
joblib.dump(clf, "used_bike_price_model.joblib.gz3", compress=1)

['used_bike_price_model.joblib.gz3']